---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-66
    driver:
      box:  opscode_centos-6.6_chef-latest.box
      box_url:  opscode_centos-6.6_chef-latest.box

suites:
  - name: default
    run_list:
      - recipe[motd::default]
    attributes:
