---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.6
    driver:
      box: opscode_centos-6.6_chef-latest.box
      box_url:  opscode_centos-6.6_chef-latest.box
      network:
      -  ["private_network", {ip: "192.168.33.35"}]
      synced_folders:
      -  ["../../chef-repo", "/chef-repo"]

suites:
  - name: node
    attributes:
