log "IP Address: #{node['ipaddress']}"
log "MAC Address: #{node['macaddress']}"
log "OS Platform: #{node['platform']}  #{node['platform_version']}"
log "Running on a #{node['virtualization']['system'] }"
log "Hostname: #{node['hostname']}"
